### ISSUE TITLE
UNCAUGHT EXCEPTION just after modifying a scss file

### ISSUE THREAD

**Issue by hillkim7** [greenpioneersolutions/meanstackjs#161]
Modifying scss file in the client\modules under the Windows OS causes the uncaught exception.
## Expected Behavior

The node detects scss file change then generates compiled css file.
## Current Behavior

Exception happened like below when I modified client\module\footer\footer.style.scss:
[UNCAUGHT EXCEPTION]
Error: ENOENT: no such file or directory, open 'C:\meanstackjs\client\styles\compiled\client\mo
ules\footer\footer.style.scss.css'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at FSWatcher.<anonymous> (C:\meanstackjs\tools\livereload\index.js:44:12)

## Possible Solution

FILE: meanstackjs\tools\livereload\index.js
**Original**:
```javascript
    scssLessWatcher.on('change', function (url) {
      var fileData = _.words(url, /[^./ ]+/g)
````
**Suggested**:
````javascript
    scssLessWatcher.on('change', function (url) {
      var fileData = _.words(url, /[^./ \\]+/g)
````

**Comment by GreenPioneer** [comment]
Thank you @hillkim7 for reporting this. I will get in for the next release which should be within the next week.

**Comment by GreenPioneer** [comment]
@hillkim7 thank you kim again and if you see anything else or have any ideas please feel free to reach out or raise an issue

**Comment by hillkim7** [comment]
I like meanstackjs what you made and the way of you implemented.
In fact, I am C/C++ programmer rather than nodejs programmer.
I am about starting my own business which is related web and embedded device.
I wish i could contribute to meanstackjs or you may share idea between us.
