### ISSUE TITLE
use lodash _.assign instead of _.merge for updates

### ISSUE THREAD

**Issue by hbenalcazar** [greenpioneersolutions/meanstackjs#273]
## Expected Behavior
In server-side controllers want to update mongo Documents that contain Array fields

## Current Behavior
using lodash _.merge() does not replace contents of the array fields

## Possible Solution
using .assign() instead replaces contents of the array fields

**Comment by GreenPioneer** [comment]
Thank you very much @hbenalcazar for contributing. I looked into and I believe you made a great point to switch over to assign.

**Comment by hbenalcazar** [comment]
Thanks, look forward to checking out 1.8 and definitely 2.0. Plan is to move to angular 2 with our project, will be happy to contribute where I can as we build out our app.
