### ISSUE TITLE
for validation errors after password reset 

### ISSUE THREAD

**Issue by hbenalcazar** [greenpioneersolutions/meanstackjs#278]
## Expected Behavior
error free redirect after resetting password

## Current Behavior
after implementing and testing with e-mailed links containing tokens, all worked right until the password was changed, then ran into undefined object errors in onIdentity().  In the sample app on heroku, seeing validation issues also

## Possible Solution
in UserClass.prototype.resetpassword replace:
>>>     }).then(self.onIdentity.bind(this), self.onIdFail.bind(this))
with:
>>>   }).then(function(success){
            self.onIdentity.bind(self)(success.data) 
            logger.success('Password reset successfully')
          }, function(error){
            self.onIdFail.bind(self)(error)
        })
    }

## Steps to Reproduce (for bugs)

See current behaviour

## Context
Implemented password reset combined with registration to force new users to click on the e-mailed reset link with the token, in our app we don't want random folks signing up from various emails

## Your Environment

* Version used: 1.7 
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome
* Operating System and version (desktop or mobile): dev/MacOS, prod/Ubuntu 16.04 
* Link to your project: private

**Comment by GreenPioneer** [comment]
👍 
Looking at getting this one in  this weekend

**Comment by GreenPioneer** [comment]
@hbenalcazar test it out and let me know if everything passes for you too. Sorry it took so long to get in i have been traveling lately and just found some time to push everything.
