### ISSUE TITLE
How can i use ngMaterial with MeanstackJS?

### ISSUE THREAD

**Issue by sureshekc** [greenpioneersolutions/meanstackjs#279]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by GreenPioneer** [comment]
@sureshekc im just getting back from vacation I'll send some to you later

**Comment by GreenPioneer** [comment]
1. `bower install angular-material --save`
2. Added all the files needed to `/config/settings.js` in `assets.js && assets.css`
3. Add `ngMaterial ` it to the `/client/modules/core/core.module.js`
4. Add some sample to code to a module of your choice and try it out

**Comment by GreenPioneer** [comment]
@sureshekc Let me know if that helps - check out the [youtube channel](https://www.youtube.com/channel/UC5lpSv5tNowgWxC9crTl97g) for more content and if I'm missing anything let me know ill make a video for it. * note i don't think i have a video for this your request so i think ill be creating one
