### ISSUE TITLE
How to add new schema in usercontroller? When I tried to add new schema in usercontroller the export is not detected. Is it possible to add new schema in usercontroller? 

### ISSUE THREAD

**Issue by psribalaji** [greenpioneersolutions/meanstackjs#281]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by GreenPioneer** [comment]
@psribalaji 

You won't want to add a new schema in the controller. you will want to create a new file for a new schema `newschemaname.model.js`.

You can copy and paste an example from the `blog.model.js` or run `npm run cli` and create one there dynamically.

Let me know if you have any other questions
