### ISSUE TITLE
File to import not found or unreadable: bootstrap.

### ISSUE THREAD

**Issue by psribalaji** [greenpioneersolutions/meanstackjs#293]
## Context
It is working fine in Windows and I developed several other modules along with this. But when I tried to change from windows to Ubuntu it is throwing me error like this immediately after "npm start"

> uncaughtException: File to import not found or unreadable: bootstrap.
> Parent style sheet: stdin
> { date: 'Thu Mar 08 2018 05:38:06 GMT+0000 (UTC)',
>   process:
>    { pid: 32329,
>      uid: 0,
>      gid: 0,
>      cwd: '/root/server/demotest',
>      execPath: '/usr/bin/node',
>      version: 'v8.9.4',
>      argv: [ '/usr/bin/node', '/root/server/demotest/index.js' ],
>      memoryUsage:
>       { rss: 82509824,
>         heapTotal: 65040384,
>         heapUsed: 36310304,
>         external: 18432908 } },
>   os: { loadavg: [ 0, 0, 0 ], uptime: 489294 },
>   trace:
>    [ { column: 16,
>        file: '/root/server/demotest/node_modules/node-sass/lib/index.js',
>        function: 'Object.module.exports.renderSync',
>        line: 439,
>        method: 'renderSync',
>        native: false },
>      { column: 21,
>        file: '/root/server/demotest/server/register.js',
>        function: 'Register.renderFrontendFiles',
>        line: 368,
>        method: 'renderFrontendFiles',
>        native: false },
>      { column: 8,
>        file: '/root/server/demotest/server/register.js',
>        function: 'new Register',
>        line: 34,
>        method: null,
>        native: false },
>      { column: 10,
>        file: '/root/server/demotest/server/register.js',
>        function: 'Object.build [as info]',
>        line: 487,
>        method: 'build [as info]',
>        native: false },
>      { column: 35,
>        file: '/root/server/demotest/server.mean.js',
>        function: 'new Mean',
>        line: 32,
>        method: null,
>        native: false },
>      { column: 16,
>        file: '/root/server/demotest/run.js',
>        function: 'run',
>        line: 15,
>        method: null,
>        native: false },
>      { column: 5,
>        file: '/root/server/demotest/index.js',
>        function: null,
>        line: 11,
>        method: null,
>        native: false },
>      { column: 30,
>        file: 'module.js',
>        function: 'Module._compile',
>        line: 643,
>        method: '_compile',
>        native: false },
>      { column: 10,
>        file: 'module.js',
>        function: 'Module._extensions..js',
>        line: 654,
>        method: '.js',
>        native: false },
>      { column: 32,
>        file: 'module.js',
>        function: 'Module.load',
>        line: 556,
>        method: 'load',
>        native: false },
>      { column: 12,
>        file: 'module.js',
>        function: 'tryModuleLoad',
>        line: 499,
>        method: null,
>        native: false },
>      { column: 3,
>        file: 'module.js',
>        function: 'Module._load',
>        line: 491,
>        method: '_load',
>        native: false },
>      { column: 10,
>        file: 'module.js',
>        function: 'Module.runMain',
>        line: 684,
>        method: 'runMain',
>        native: false },
>      { column: 16,
>        file: 'bootstrap_node.js',
>        function: 'startup',
>        line: 187,
>        method: null,
>        native: false },
>      { column: 3,
>        file: 'bootstrap_node.js',
>        function: null,
>        line: 608,
>        method: null,
>        native: false } ],
>   stack:
>    [ 'Error: File to import not found or unreadable: bootstrap.',
>      'Parent style sheet: stdin',
>      '    at Object.module.exports.renderSync (/root/server/demotest/node_module                                                                                                             s/node-sass/lib/index.js:439:16)',
>      '    at Register.renderFrontendFiles (/root/server/demotest/server/register                                                                                                             .js:368:21)',
>      '    at new Register (/root/server/demotest/server/register.js:34:8)',
>      '    at Object.build [as info] (/root/server/demotest/server/register.js:48                                                                                                             7:10)',
>      '    at new Mean (/root/server/demotest/server.mean.js:32:35)',
>      '    at run (/root/server/demotest/run.js:15:16)',
>      '    at Object.<anonymous> (/root/server/demotest/index.js:11:5)',
>      '    at Module._compile (module.js:643:30)',
>      '    at Object.Module._extensions..js (module.js:654:10)',
>      '    at Module.load (module.js:556:32)',
>      '    at tryModuleLoad (module.js:499:12)',
>      '    at Function.Module._load (module.js:491:3)',
>      '    at Function.Module.runMain (module.js:684:10)',
>      '    at startup (bootstrap_node.js:187:16)',
>      '    at bootstrap_node.js:608:3' ] }

## Your Environment
Ubuntu Server 16.04
npm version 3.10.8
node version 7.0.0

**Comment by GreenPioneer** [comment]
https://github.com/greenpioneersolutions/meanstackjs/blob/master/server/register.js#L372

Can you go verify bootstrap-sass downloaded properly ?

**Comment by GreenPioneer** [comment]
@psribalaji  if you want to try this [branch](https://github.com/greenpioneersolutions/meanstackjs/tree/feature/%23292_update_stack)   #126 

I am finishing up release 1.9 currently and we are moving off of bower to npm which should take care of your issue
