### ISSUE TITLE
Error: Blog creator's name is not shown

### ISSUE THREAD

**Issue by nafiskarim** [greenpioneersolutions/meanstackjs#89]
Go to "List Blog" from dropdown menu by clicking - "Examples" and then "List Blog".
Now there will be a list of blogs written including blog title, created date and description. But it's not showing the name of blog creator/writer. It should be showing the name after the word "by"
Here's a screenshot of it. I hope it helps :)
![screen shot 2016-08-14 at 02 08 54](https://cloud.githubusercontent.com/assets/4218138/17646313/7a03e4d0-61c4-11e6-964c-78c86285c9dc.png)

**Comment by GreenPioneer** [comment]
try this and let me know if it works for you 
``` 
//list.view.html
by {{value.user.profile.name}} - {{value.created |date:'medium'}}
```

**Comment by nafiskarim** [comment]
Hey, It did not solve the problem for me. Note that it does not show creator's name no matter if you are logged in or logged out.

**Comment by GreenPioneer** [comment]
Can you log your ``` {{value}} ```

**Comment by nafiskarim** [comment]
yes. it returns an object.

**Comment by GreenPioneer** [comment]
what does it return ?

**Comment by nafiskarim** [comment]
{"_id":"57b19e47ce7737ff5d68e598","title":"new blog posts","content":"description for new blog post","user":"57b1769468c78126594a54a0","__v":0,"created":"2016-08-15T10:49:43.716Z"}

**Comment by GreenPioneer** [comment]
go to the web browsers dev tools and find this call
`Request URL:http://localhost:3000/api/v1/Blog`
then check that the response.quer. populateId  ="user "

**Comment by nafiskarim** [comment]
Request url: http://localhost:3000/api/v1/Blog?noCache=1471419250850
Response: {"actions":{},"query":{"filter":{},"gt":1,"lt":0,"gte":false,"lte":false,"in":[],"ne":false,"nin":false,"regex":false,"options":false,"size":false,"all":false,"equals":false,"find":false,"aggregate":false,"lean":false,"skip":0,"sort":"","limit":20,"select":"","populateId":"","populateItems":"","deepPopulate":"","where":"","error":{},"warning":{}},"count":7,"itemPerPage":7,"data":[{"_id":"57ac8cd9520636293504d485","title":"my first blog","content":"this is my first blog.","user":"57ac8cae520636293504d484","__v":0,"created":"2016-08-11T14:34:01.108Z"},{"_id":"57ac8f11e2cb944435a90b6f","title":"another post","content":"description of another blog post","user":"57ac8cae520636293504d484","__v":0,"created":"2016-08-11T14:43:29.573Z"},{"_id":"57ac9577675d3db735f07bd2","title":"3rd post","content":"description","user":"57ac8cae520636293504d484","__v":0,"created":"2016-08-11T15:10:47.964Z"},{"_id":"57b176b968c78126594a54a1","title":"First blog from fred","content":"Some description from fred","user":"57b1769468c78126594a54a0","__v":0,"created":"2016-08-15T08:00:57.449Z"},{"_id":"57b19d98ce7737ff5d68e596","title":"another blog from Fred","content":"description","user":"57b1769468c78126594a54a0","__v":0,"created":"2016-08-15T10:46:48.122Z"},{"_id":"57b19dcace7737ff5d68e597","title":"hmm","content":"descr hmm","user":"57b1769468c78126594a54a0","__v":0,"created":"2016-08-15T10:47:38.592Z"},{"_id":"57b19e47ce7737ff5d68e598","title":"new blog posts","content":"description for new blog post","user":"57b1769468c78126594a54a0","__v":0,"created":"2016-08-15T10:49:43.716Z"}],"user":{},"type":"blog","success":true}

**Comment by GreenPioneer** [comment]
https://github.com/greenpioneersolutions/meanstackjs/blob/master/configs/settings.js#L141

Does your code say this ? cause your response indicates you changed this

**Comment by nafiskarim** [comment]
yes. it's the same -
query: {
      sort: '',
      limit: 20,
      select: '',
      filter: {},
      populateId: 'user',
      populateItems: '',
      lean: false,
      skip: 0,
      where: '',
      gt: 1,
      lt: 0,
      in: [],
      equal: '',
      errorMessage: 'Unknown Value'
    }

**Comment by GreenPioneer** [comment]
Did you change anything else ?
The problem is the call isnt sending a populate through.
#92 I am going to remove that automation that is being used in the blog which will make everything work for you
